### ISSUE TITLE
Gratitude and request to take over your status bar :)

### ISSUE THREAD

**Issue by littlebee** [mupchrch/split-diff#100]
Hi,

First let me sincerely thank everyone who has contributed to this fine working plugin!  Without it, [git-time-machine](https://github.com/littlebee/git-time-machine) would kinda suck.  Or I'd just be showing the diff as the very first versions did.  It was a suggestion / idea / issue someone filed on gtm in those first few weeks.  Sincerely, thank you and for all your help since @mupchrch 

I've been slowly, slowly working on v2 of git-time-machine.   A couple of cool features like being able to select any two revs to diff and allowing stepping forward and backward through commits are planned.

For the later,  I was going to add a control bar above the timeplot, ...  And look at that, you already added it for me, along with another feature I wanted - go to next/prev diff within a file.

Do you have anything planned to fill the space in your status / control bar?   

Not asking you to do anything, I can inject the selectors into your status bar from gtm.

Thanks again!
<img width="1372" alt="pasted_image_3_26_17__9_20_am" src="https://cloud.githubusercontent.com/assets/593784/24333035/fc70e7d2-1205-11e7-9403-2344ce7de3f5.png">

**Comment by mupchrch** [comment]
Love git-time-machine! So happy I've had any kind of involvement in such a cool package 😄 

> Do you have anything planned to fill the space in your status / control bar?

Nothing planned at the moment. Once you dig into it, let me know if there's anything I can do on my end to make your life easier!
