### ISSUE TITLE
It is very different depending on the setting(soft wrap).

### ISSUE THREAD

**Issue by pluto1019** [mupchrch/split-diff#101]
Hi, @mupchrch . I think so. If the editor 'soft wrap' setting are turned on, I want to save the setting and change it when the split-diff is run. If the editor 'soft wrap' setting aren't on, just ignore them.
Right now, the left pane and the right pane are too different.

![default](https://cloud.githubusercontent.com/assets/7157572/24383485/15e97786-1398-11e7-8963-72006e661f18.PNG)

**Comment by mupchrch** [comment]
My interpretation of what is being proposed here is to add a setting that will automatically turn off soft wrap while diffing, and turn it back on when finished diffing.
