### ISSUE TITLE
[Bug] "atom core" deprecation after Split Diff: Toggle

### ISSUE THREAD

**Issue by ooJerryLeeoo** [mupchrch/split-diff#102]
Here's the deprecation message:

```
Assigning editor 260's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.

TextEditorComponent.measureDimensions - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1012:20
TextEditorComponent.becameVisible - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:295:12
TextEditorComponent.checkForVisibilityChange - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:994:16
atom-text-editor.attachedCallback - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22
atom-pane-axis.childAdded - /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:95:12
Function.module.exports.Emitter.simpleDispatch - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14
```

**Comment by mupchrch** [comment]
Hello, and thanks for the contribution! This is an issue with a specific Atom API and I have previously logged https://github.com/atom/atom/issues/13736 for it. As of yet, it hasn't been looked into, so please make some noise over there so it gets fixed!

**Comment by ooJerryLeeoo** [comment]
@mupchrch But if I activate `split-diff` from `git-plus`, atom doesn't send me the deprecation.

**Comment by ooJerryLeeoo** [comment]
@mupchrch Any news on this issue ?

**Comment by mupchrch** [comment]
Sorry, glad you asked because I would have forgot to investigate since this issue is closed! Reopening - will hopefully get time to look tonight.

**Comment by mupchrch** [comment]
Ugh forgot to comment my findings, sorry @ooJerryLeeoo!

It looks like `git-plus` is setting up `split-diff` manually instead of just calling the toggle command. `git-plus` is feeding two editors directly to one of my API's and bypassing the `split-diff` logic that finds the visible editors and splits panes if there aren't two found side by side (the logic mentioned in atom/atom#13736). This is the logic that is causing the deprecation warning.

**Comment by borishere** [comment]
The bug is still there. And I don't have `git-plus` package.
