### ISSUE TITLE
Duplicated toolbars

### ISSUE THREAD

**Issue by schultzern** [mupchrch/split-diff#103]
Hi!

I'm experience duplicated toolbars from the split-diff package. I use the git-time-machine package and it seems to enable split-diff when I use it. However the buttons are unusable. And when I click them another split-diff toolbare is displayed, and the new buttons work as expected. See picture.
![tmp1](https://cloud.githubusercontent.com/assets/16745064/24911211/808af424-1eca-11e7-9204-aeae90664411.png)

System info:
..........................................
CentOS 7.2

Atom : 1.15.0
Electron: 1.3.13
Chrome : 52.0.2743.82
Node : @6.5.0

Packages:
git-time-machine@1.5.9
split-diff@1.3.0

**Comment by mupchrch** [comment]
I think the issue you logged on git-time-machine is more valid https://github.com/littlebee/git-time-machine/issues/110.

This isn't really a bug with split-diff, more of a bug with how it's being used by git-time-machine. That being said, I'll leave this open so I remember to figure out how I can more easily accommodate what git-time-machine is doing.

**Comment by schultzern** [comment]
Thanks for the feedback!

**Comment by mupchrch** [comment]
Closing this as I held up my end of the bargain and am waiting on my PR to `git-time-machine` to hopefully get merged https://github.com/littlebee/git-time-machine/pull/120
