### ISSUE TITLE
Pane is not split under `Atom1.17.0-beta2`

### ISSUE THREAD

**Issue by ooJerryLeeoo** [mupchrch/split-diff#104]
As the title, here's an example:

![split-diff-bug](https://cloud.githubusercontent.com/assets/20783502/25091077/b997855e-23b9-11e7-9ca9-8cad7b4c56fe.gif)

**Comment by ooJerryLeeoo** [comment]
@mupchrch Can you take a look ?

Thanks.

**Comment by mupchrch** [comment]
Will take a look tonight.

**Comment by mupchrch** [comment]
Thank you for the heads up, @ooJerryLeeoo! (gifs are always appreciated 😄)
