### ISSUE TITLE
Diffing large files hangs/freezes atom

### ISSUE THREAD

**Issue by johnsoga** [mupchrch/split-diff#107]
When attempting to diff two relatively large file (~1200 lines each). Atom tends to hang or freeze and often needs to be restarted. Maybe this is due to the fact that it has to diff again every time a modification is made?

**Comment by mupchrch** [comment]
Hi @johnsoga, what version of Atom are you on? What version of split-diff are you on? What is your operating system, amount of RAM, CPU etc?

I ask because I am not seeing Atom freeze during a diff of files that large - just a loading indicator (that shouldn't block the UI) as it computes the diff.

**Comment by ChrisRiddell** [comment]
@mupchrch I'm having almost the same issue where atoms slows down and just says computing diff forever waited over 20mins, trying to split-diff a file with over 400,000 lines. It use to work and give me the diff in no time at all but now it does not.

Computer Ryzen 1600, 8GB Ram, Tried Atom 1.18 and 1.19b2, split-diff 1.4.3 and minimap-split-diff 0.3.7

**Comment by johnsoga** [comment]
this seems to have gone away in newer versions.
