### ISSUE TITLE
Submodule support

### ISSUE THREAD

**Issue by MasonRemaley** [mupchrch/split-diff#112]
I'm having trouble getting the plugin to work in a git project that uses submodules--it just compares the files in the submodule to empty files. Let me know if I'm just misunderstanding how it should be used, but I think this is probably a bug. It looks like other atom packages have run into and solved what seems like the [same problem](https://github.com/akonwi/git-plus/issues/48).

**Comment by mupchrch** [comment]
Thanks for the link, that'll be helpful! Probably a bug, never heard of submodules tbh 😆

**Comment by MasonRemaley** [comment]
Haha no problem! :) Let me know if you have any trouble recreating the issue or anything!
