### ISSUE TITLE
New files opening in tree dock instead of main pane

### ISSUE THREAD

**Issue by questing-beast** [mupchrch/split-diff#115]
Starting with v1.4.0, diffing two files occasionally results in a third file popping up in the tree view area (maybe called the "dock"?). I'm not sure if this is an Atom issue affecting split-diff or a split-diff issue affecting Atom (once a file opens in the dock, the next file opened will open there too).  

<img width="1358" alt="screen shot 2017-06-14 at 17 03 24" src="https://user-images.githubusercontent.com/25324320/27154551-6a215a12-5123-11e7-9be2-f78c82c056f2.png">

(Cross-posted from https://discuss.atom.io/t/new-files-open-in-the-tree-view-area/43994)

**Comment by mupchrch** [comment]
@questing-beast Would you mind running `apm list --installed --bare` in cmd prompt and pasting the output here? Want to see what packages you have installed, maybe one of them is affecting split-diff?

**Comment by questing-beast** [comment]
Sure! Thanks for your help.

C:\Program Files\eXtyles\TestSuite>apm list --installed --bare
atom-beautify@0.29.17
atom-monokai@0.10.9
auto-detect-indentation@1.3.0
block-comment@0.4.3
color-picker@2.2.5
file-icons@2.1.7
git-plus@7.9.2
minimap@4.26.8
minimap-split-diff@0.3.7
monokai-seti@0.9.0
open-recent@5.0.0
pigments@0.39.1
seti-ui@1.6.1
split-diff@1.2.0

seti-syntax@1.1.2

**Comment by mupchrch** [comment]
Hm, it says you have split-diff v1.2.0. Is that true? Maybe the package update failed or something? What version of Atom are you on?

**Comment by questing-beast** [comment]
Wow, thanks for catching that -- apparently something had gone wrong with the package updater (https://discuss.atom.io/t/solved-fetching-outdated-packages-and-themes-failed/39539) and I hadn't noticed. Just ran a few diffs with no problems, including #116.
