### ISSUE TITLE
ctrl-option-d doesn't work to toggle (why did you change this!)

### ISSUE THREAD

**Issue by michael-crawford** [mupchrch/split-diff#118]
I was used to using ctrl-option-t to toggle, today I just noticed this no longer worked.

I found the new keybinding should be ctrl-option-D, but this doesn't work, with or without shift. Instead, it deletes a character.

I don't know why you'd change this with no warning, and without a way to change it back for those used to the prior binding.

**Comment by michael-crawford** [comment]
I noticed in the release notes you changed this in the last release to avoid a conflict on linux. So that explains the reason.

I'm cool with the change if it's necessary - it just has to work! I use this all the time, and currently it's broken, and instead deletes a character. On an iMac, latest MacOS.

**Comment by ooJerryLeeoo** [comment]
Duplicated #117

**Comment by mupchrch** [comment]
@michael-crawford You can always change keybindings to whatever you want. Go to the top menu bar, Atom > Keymap...

Then paste the below text into that file and save it
```
'atom-workspace':
  'ctrl-alt-t': 'split-diff:toggle'
```
