### ISSUE TITLE
Pane is not split under Atom1.19.0-beta1 (again)

### ISSUE THREAD

**Issue by ooJerryLeeoo** [mupchrch/split-diff#120]
As the title.

**Comment by mupchrch** [comment]
Hm it's splitting for me, but I can't scroll the right editor.

**Comment by ooJerryLeeoo** [comment]
I've find out the problem is `minimap-selection`.

**Comment by mupchrch** [comment]
I think my latest commit will fix the issue. Please reopen if the update I push out in a few minutes doesn't help your situation.
