### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by omarlemorac** [mupchrch/split-diff#122]
In styles/split-diff.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by mupchrch** [comment]
@omarlemorac Is this still an issue? I am not seeing this. What version of split-diff are you using? What version of atom are you using? Thanks.

**Comment by mupchrch** [comment]
@omarlemorac I am going to close this since I never received a response. Please reopen and let me know if you are still seeing this issue.
