### ISSUE TITLE
TreeView toggling when typing

### ISSUE THREAD

**Issue by cricket007** [mupchrch/split-diff#125]
**Details**
Atom v1.18.0  
Platform: macOS Sierra

**Brief description**  
When I toggle/enable the Split Diff when I have a project opened and type anything, it is toggling the TreeView almost immediately on keystroke. When this happens, the focus is then taken away from the editor, and instead placed on the TreeView. 

I don't believe this behavior was happening prior to the 1.18.0 release

**Comment by cricket007** [comment]
Did you mean to close this?

**Comment by mupchrch** [comment]
Yes, I just fixed this in master and will push out an update relatively soon.

**Comment by cricket007** [comment]
Ah, my bad. Didn't see the commit message
