### ISSUE TITLE
Scroll placement moving during modification during diff

### ISSUE THREAD

**Issue by johnsoga** [mupchrch/split-diff#129]
I've noticed that while diff'ing if make a modification to a file the the cursor will stay where i just made the modification but the screens will scroll up quite a bit. This only seems to happen if I'm modifying in reverse (from bottom of file to the top)

**Comment by Bengrunt** [comment]
Hi there,

I love split diff, but lately it started behaving strangely in a very similar manner that @johnsoga mentioned.

When I split diff two files in works fine, but as soon as I start editing one of the files, split diffs tries to updates the diffs immediately and then the output of both files gets screwed up with multiple empty lines being added kind of randomly. Additionally, it doesn't matter whether you start editing from the bottom of the file or not. After two edits you can't use it anymore.

The only solution to get back to a normal output is to toggle off split diff, close both files and reopen them.

I'm using Atom v1.19.6 with split-diff v1.5.1 (and minimap-split-diff v0.3.7) on Ubuntu Xenial. My system is pretty much up to date.

Hope you can find a solution.
Thanks a lot!

**Comment by mupchrch** [comment]
@johnsoga @Bengrunt sorry for the super late response. I had tried to reproduce back then, but I was never able to see anything consistent. Any chance you guys are still seeing this issue?

**Comment by johnsoga** [comment]
nope I'm not seeing it anymore so I'd say this can be closed
