### ISSUE TITLE
Cannot use 2 higlight classes at once

### ISSUE THREAD

**Issue by trin-cz** [mupchrch/split-diff#132]
Commit #ae200821 is causing error, because of concatenating 2 classes with space.

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('split-diff-line split-diff-added') contains HTML space characters, which are not valid in tokens.
/usr/share/atom/resources/app/src/lines-tile-component.js:170
Hide Stack Trace
Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('split-diff-line split-diff-added') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at LinesTileComponent.buildLineNode (/usr/share/atom/resources/app/src/lines-tile-component.js:170:34)
    at LinesTileComponent.updateLineNodes (/usr/share/atom/resources/app/src/lines-tile-component.js:123:38)
    at LinesTileComponent.updateSync (/usr/share/atom/resources/app/src/lines-tile-component.js:73:16)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom/resources/app/src/tiled-component.js:55:25)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom/resources/app/src/tiled-component.js:18:18)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom/resources/app/src/text-editor-component.js:266:40)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:198:18)
    at /usr/share/atom/resources/app/src/text-editor-component.js:325:34
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:223:15)
    at /usr/share/atom/resources/app/src/view-registry.js:3:65

**Comment by mupchrch** [comment]
@trin-cz I am not seeing the same issue. What version of Atom are you on? What OS? Thanks

**Comment by skylerlee** [comment]
Hi, @trin-cz. Thanks for your feedback.

I'm the contributor of this commit.
This is a bug of TextEditor::decorateMarker method, and should have been fixed by [this commit - Allow multiple space-delimited classes for highlight decorations](https://github.com/atom/atom/commit/986e8bf85fd67c03a587f8bd225ea69e073735a5) at version [v0.184.0 of Atom](https://github.com/atom/atom/releases/tag/v0.184.0).

Can you upgrade your Atom and see whether the problem still exist?

**Comment by trin-cz** [comment]
Hi, @mupchrch and @skylerlee . I'm on Atom v0.18.0, so that's it. Please consider this invalid. I cannot upgrade, I downgraded because of minimap issue https://github.com/atom-minimap/minimap/issues/626 . So I just downgraded split-diff to v1.5.0.

Split diff is great, I use it very often. Being able to see what the code in git looked like before my changes and compare. Also I use it to compare outputs from tests. Sometimes tests say, that output doesn't match. But the output is one line over several pages and it's hard to find the difference. So I just paste the outputs in atom, enable softwrap and compare the 2 tabs with split-diff.

Thanks for the good work!

**Comment by mupchrch** [comment]
>Please consider this invalid.

Not truly invalid, ideally you should not have been able to update to the new package version since it isn't working with that version of Atom. If I had known, I would have scoped the update to be for versions of Atom after v0.18.0.

Do you think it is worth unpublishing the new package version and republishing it scoped for after v0.18.0? Not sure how hard it is.

**Comment by trin-cz** [comment]
Not worth doing it just for me. Only if you ever find, that I'm not the only one having this problem.

**Comment by zauker** [comment]
Hi, received the same issue using Atom version 1.18.0 on Mac with Sierra.
Upgrading Atom to version 1.21.0 I do no receive more issue.

![image](https://user-images.githubusercontent.com/932680/31272333-da906a48-aa8a-11e7-9dd1-1f6e2f099638.png)

**Comment by mupchrch** [comment]
Closing because atom v1.18 is pretty old by now so hopefully no one runs into this anymore. Also I've scoped the package higher in my latest commit to guard against something like this.
