### ISSUE TITLE
Atom hang when navigating up and down

### ISSUE THREAD

**Issue by sanusi87** [mupchrch/split-diff#136]
Atom hang and I have to force close to restart, when I want to move to next or previous diff.

**Comment by DSamuylov** [comment]
I have the same problem. It also hangs some time when you would like to toggle diff. Because of it, I should stop using the plugin... I hope it will be fixed soon.

**Comment by lukasolson** [comment]
For me, it's only if I use the keyboard shortcuts. It seems to be fine when using the mouse keys.

I opened the dev tools to see what was happening, and for some reason the editor crashes when I try to step through the first line of `nextDiff()`... So it might actually be some sort of Atom bug.

**Comment by mrdegger** [comment]
I have the problem, when the next diff, i go to, is bigger in height than the displayable rows.

**Comment by Zakini** [comment]
It might have something to do with soft wrap. Enabling 'Turn off soft wrap' seemed to fix the issue for me.

**Comment by farovitus** [comment]
i have the same issue, and it's pretty annoying and happens almost in every session. 
I hope they fix it soon.

**Comment by gdebojyoti** [comment]
Thanks a lot for solving this issue. 👍
