### ISSUE TITLE
Installing “split-diff@1.5.1” failed

### ISSUE THREAD

**Issue by jlmoody** [mupchrch/split-diff#138]
Atom: 1.20.1 x64
OS: Mac OS X 10.12.6

Message received while trying to install package:

```
Installing “split-diff@1.5.1” failed.Hide output…
Unable to download https://www.atom.io/api/packages/split-diff/versions/1.5.1/tarball: 500 Internal Server Error Application error
```
If additional information is needed please let me know, happy to help.

**Comment by mupchrch** [comment]
Looks like network error, @jlmoody have you managed to get it installed yet? Maybe atom.io was having trouble serving files at the time.

**Comment by jlmoody** [comment]
@mupchrch It does appear atom.io was having issues serving the package. I have succesfully installed split-diff 1.5.1 at this time. Thank you.
