### ISSUE TITLE
stop split-diff from updating current diff

### ISSUE THREAD

**Issue by code-beans** [mupchrch/split-diff#139]
I have relatively large files to diff (10k lines), so updating takes a couple of minutes which is fine for me.
Once split-diff created a diff for me and I am manually making changes it keeps updating the diff though, starting the whole process all over again. 

How do I make it stop updating? I tried disabling it but this would also hide the diff itself.

I want it to create the diff once, and only update if I say so.

**Comment by mupchrch** [comment]
I think this would be a good setting. Something that would disable the automatic re-diff.

**Comment by Bengrunt** [comment]
I could not agree more.
Large file comparisons can simply not be handled :/

:+1:
