### ISSUE TITLE
Syntax highlighting broken

### ISSUE THREAD

**Issue by WilliamNurmi** [mupchrch/split-diff#141]
Recently, split-diff's syntax highlighting has broken for me. Split-diff has been working flawlessly so far, but suddenly I'm having no syntax highlighting on the original-side (see below). Restart, changing package settings, or Atom (syntax) themes does not fix the issue. Any idea what's wrong here?

split-diff 1.5.2
Atom 1.24.0 (theme: Atom Dark, syntax  theme: Base16 Tomorrow Dark)
macOS 10.13.3

<img width="1383" alt="screen shot 2018-02-19 at 9 57 55" src="https://user-images.githubusercontent.com/7571321/36367829-1e893c38-155d-11e8-91a7-442004d54135.png">

**Comment by ZenekeZene** [comment]
+1

**Comment by ChenXiyu** [comment]
Is the root cause of this issue similar with https://github.com/akonwi/git-plus/issues/717 ?

**Comment by mupchrch** [comment]
`TextEditor.setGrammar` and `TextEditor.getGrammar` functions were deprecated due to the changes in https://github.com/atom/atom/pull/16087. Updated to use these new language mode APIs.

**Comment by mupchrch** [comment]
@Igor10k That is a great question... Publishing this patch now!

**Comment by mizmaar3** [comment]
@mupchrch its back again in Atom 1.32.1 unfortunately
