### ISSUE TITLE
Scroll Sync isnt

### ISSUE THREAD

**Issue by bsussman** [mupchrch/split-diff#143]
Running 1.26.0B0
split-sync 1.5.2

the two panes are not starting synced nor staying synced - it seems that the newly opened pane does not honor the 'turn off soft wrap' setting.  I must turn off soft wrap in the main settings->editor to keep the diff in sync.

**Comment by mupchrch** [comment]
Investigation notes:

This package is creating a text editor by calling `atom.workspace.buildTextEditor`. We are definitely calling `setSoftWrap` but it doesn't seem to be sticking. I'd imagine something about opening a text editor is asynchronous and is reapplying the global settings to the text editor after we have set it. Putting a debugger after the `buildTextEditor` call will cause my soft wrap stuff to work correctly.

I tried passing the `softWrapped` param as `false` to `atom.workspace.buildTextEditor`, but you can see on https://github.com/atom/atom/blob/v1.28.2/src/text-editor-registry.js#L112 that the passed params are being overridden by the global settings.
