### ISSUE TITLE
Feature request: Automatic Encoding

### ISSUE THREAD

**Issue by WashirePie** [mupchrch/split-diff#148]
Would it be possible to use [auto-encoding](https://atom.io/packages/auto-encoding)
as a possible Encoding type?

I've got the Issue that I work with files with different Encoding types. For example:
- I've set my main Encoding type ```Settings/Core/File Encoding``` to ```UTF-8```
- I edit a file which natively is ```Windows 1252 ``` encoded - save it and  Diff it to an earlier Version of the same file. (Note: ```auto-encoding``` switches my encoding type automatically to ```Windows 1252``` in this scenario)
- The Diff will display all vocals like ```ä, ö or ü``` as differences since ```UTF-8``` uses a different Symbol for them 

~~This is indeed an uncommon scenario and it will likely be gone in 1 - 2 years from now since ```UTF-8``` is slowly becoming the standard where I work.~~ I'd be glad if you could look into it!

**Comment by WashirePie** [comment]
#EDIT:
Since this seems to be a bigger Issue than I tought - (https://github.com/atom/encoding-selector/issues/24) - it would be nice for now to be able to set the encoding type in the Diff View:
(Something like this)
![atom-issue3](https://user-images.githubusercontent.com/38029550/41899956-2083afea-791d-11e8-908c-dc64773b70ff.png)

**Comment by WashirePie** [comment]
# EDIT:
Upon further digging, it looks like the problem lies within the time-machine package.
I've created a thread https://github.com/littlebee/git-time-machine/issues/135
This one can be closed.

**Comment by mupchrch** [comment]
Thanks for taking a look at that @WashirePie
