### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by dspies-leapyear** [mupchrch/split-diff#151]
I'm running into this issue: https://github.com/atom/atom/issues/17010
when I toggle on `split-diff`.

<img width="705" alt="screen shot 2018-10-16 at 8 33 16 am" src="https://user-images.githubusercontent.com/25259959/47028513-60ea6c00-d11e-11e8-9913-b1b9c8cf2314.png">

Instead of getting the old file, the RHS is empty (visible in the screenshot. The LHS is the file as it is currently with green markings for lines which have changed). It seems to only happen on some files within the repo, but it happens consistently on those.

------------

macOS High Sierra 10.13.6

```
$ atom --version
Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
$ apm show split-diff
split-diff
├── 1.5.3
├── https://github.com/mupchrch/split-diff
├── A split pane diff tool.
├── 496758 downloads
└── 605 stars
```

**Comment by jaibatrik** [comment]
Yeah, this has rendered the package unusable for me.

**Comment by philayres** [comment]
I think that there may be an issue with git somewhere. I just tried the `git-time-machine` package and it complains on the last commit with `Could not retrieve revision for <filename> (128)` but works for previous commits. 

Perhaps there is a common issue between the two packages. 

I have checked `git diff` on the command line and it works fine. Also **meld** version control diff works. So I'm fairly sure it is not an issue with my git repo.

My git version is 2.7.4

**Comment by dspies-leapyear** [comment]
```
$ git --version
git version 2.17.2 (Apple Git-113)
```

**Comment by hSaria** [comment]
Same issue here. I've had to force-install the 1.5.2 version.

**Comment by dspies-leapyear** [comment]
@hSaria How do you do that?

**Comment by hSaria** [comment]
@dspies-leapyear on terminal, type
```apm install split-diff@1.5.2```

You can do the same for any package, just run `apm list` to list all packages, then use the `apm install` command with the format `package-name@version-number`.

**Comment by peter92427** [comment]
Happens to me too, see above issue #18590 for the report.
It seems it depends on the contents of the pasted text.

**Comment by multinerd** [comment]
[Enter steps to reproduce:]

1. Open `Atom`
2. From toolbar `Packages` > `Split Diff` > `Toggle`
3. Error thrown when: 
    - Merely clicking on the right side
    - Trying to paste (via keyboard) on right side

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At C:\Users\mikeh\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11

TypeError: Cannot read property 'tags' of undefined
    at TextMateHighlightIterator.seek (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:560161)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:1102810)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:89306)
    at DisplayLayer.getScreenLine (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:89203)
    at TextEditor.screenLineForScreenRow (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:13891)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:107298)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:98589)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:95149)
```

### Commands

```
     -1:18.9.0 split-diff:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:13.1.0 core:paste (input.hidden-input)
     -1:03.9.0 core:select-all (input.hidden-input)
  3x -1:03.7.0 core:paste (input.hidden-input)
     -0:52.6.0 split-diff:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:48.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
language-batchfile 0.7.5 
split-diff 1.5.3 
```

**Comment by mupchrch** [comment]
I still can't reproduce this problem. @hSaria are you saying that the previous version of the package works and no error is thrown? Does syntax highlighting of the right side work?

**Comment by hSaria** [comment]
@mupchrch Yeah, the previous version works fine but it does not set the grammar of the document automatically. If, for example, I have a document with the Python grammar/language set, when I open a split-diff tab, it will default to plain-text. Apart from that, everything else is fine.

**Comment by hSaria** [comment]
I've fixed it and done a bit of testing. Works as expected (editor2 gets the grammar of editor1 without any issues). The pull request is #157

**Comment by mupchrch** [comment]
Marking the issue as fixed, thanks to @hSaria

**Comment by multinerd** [comment]
issue seems fixed to me
