### ISSUE TITLE
Syntax highlighting broken in Atom 1.32.1

### ISSUE THREAD

**Issue by mizmaar3** [mupchrch/split-diff#153]
Same like: https://github.com/mupchrch/split-diff/issues/141?_pjax=%23js-repo-pjax-container

but in latest Atom ver  1.32.1

**Comment by waldnzwrld** [comment]
I found that using `split diff:enable` and `split diff:disable` shows the correct highlighting. It's only when using `split diff:toggle` that I lose syntax highlighting.  Also once untoggled syntax highlighting is broken for the primary file (original not compared) until I set the syntax again.

**Comment by mupchrch** [comment]
@mizmaar3 @waldnzwrld I believe this might be fixed by #157. I've just released a new version of the package, let me know if it fixes this issue and we can close this out, thanks!

**Comment by waldnzwrld** [comment]
Yup!! Everything is toggling the way it should!!! Thanks @mupchrch !!

**Comment by mupchrch** [comment]
Pass along the thanks to @hSaria :)
