### ISSUE TITLE
Feature Request: Disable Auto-Diff

### ISSUE THREAD

**Issue by DiegoLpVn** [mupchrch/split-diff#154]
Every time I try to Diff large files, as soon as I make a change, the package auto-diffs again, sometimes it takes even a few minutes. 
I would like an option / command to stop auto-diff and to diff again whenever I want.

Thanks :)

**Comment by mupchrch** [comment]
I totally agree, this would be a fantastic feature. Closing as this is a duplicate of #139, but your request has absolutely been heard.
