### ISSUE TITLE
Cannot install Split-diff

### ISSUE THREAD

**Issue by Florian-9** [mupchrch/split-diff#171]
I am on Mojave and when I try to install split-diff 1.6.1 package it's giving me the following error. How can I resolve it?

Installing “split-diff@1.6.1” failed.Hide output…

npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/diff failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zzzz/.atom/.apm/_logs/2020-01-13T15_03_54_386Z-debug.log

**Comment by Florian-9** [comment]
This error comes up when I try to install any of the packages

**Comment by mupchrch** [comment]
@Florian-9 I'd recommend asking on https://discuss.atom.io/. It sounds like it's an overall issue with Atom or npm. They'd understand more over there. Sorry I couldn't be of any help!

Perhaps you could run this command as a workaround https://github.com/npm/npm/issues/9580#issuecomment-166605021
