### ISSUE TITLE
[Windows] undefined is not a function - atom.workspace.isTextEditor

### ISSUE THREAD

**Issue by lwblackledge** [mupchrch/split-diff#19]
Split-diff does not work on Windows because of this error. It fires in `getVisibleEditors` when trying to determine if the active pane item is a `TextEditor`.

Looking at `atom.workspace.getTextEditors`, a better option might be to use `instanceof`:

`if (activeItem instanceof TextEditor) {`

I'll make a PR with the suggested change, but I tested this on Windows by modifying the file directly and it fixed my issue.

**Comment by mupchrch** [comment]
Thanks! Just curious, what version of Atom are you on?

**Comment by lwblackledge** [comment]
I didn't check, I'll take a look tonight.
