### ISSUE TITLE
Next/Previous Diff starts from beginning of file after change

### ISSUE THREAD

**Issue by DallasO** [mupchrch/split-diff#25]
(First time bringing up an issue, so sorry if I do something wrong)

When using Move to Next/Prev Diff commands, if you make a change to the file you are editing, and try to find the Next Diff, it starts back at the first diff of the file.

Expected behavior would be to move to the diff after the change.

**Comment by mupchrch** [comment]
Thanks! That was a silly mistake by me. It should be fixed now if you grab v0.7.1.
