### ISSUE TITLE
Broken in Atom-Beta 1.7

### ISSUE THREAD

**Issue by chrisco314** [mupchrch/split-diff#28]
Hi,

I'm not sure if this is expected behavior, but I could not get this to work with the Atom Beta 1.7. It would flash momentarily, and then the diff highlights would disappear again.

It does work on Atom 1.54 though (and it's really helpful) 

- Thanks.

**Comment by mupchrch** [comment]
Thanks for the heads up! I should have the fix out tomorrow.

**Comment by mupchrch** [comment]
I stupidly had a call to disable in my serialize function. However this led me to discover a bug with Atom 1.7 beta since I don't think the serialize method should be called on every click in an editor. My issue is fixed but I have logged atom/atom#11408 as a result of my investigation.
