### ISSUE TITLE
Sync Horizontal Scrolling

### ISSUE THREAD

**Issue by DallasO** [mupchrch/split-diff#29]
It would be nice to have a setting to be able to sync horizontal scrolling while split-diff is enabled.

**Comment by pistou** [comment]
:+1:

**Comment by mupchrch** [comment]
:+1:

**Comment by pistou** [comment]
I may be mistaken, but I don't see any checkbox in the settings to toggle this option.

At this point, we have to manually set `syncHorizontalScroll: true` in the **config.cson** file

**Comment by mupchrch** [comment]
Glad you found a workaround. I don't really know why this would be occurring. The only thing I can think of is maybe the package's config-schema.cson file was not updated when you updated? You could try uninstalling the package and reinstalling. If that is the case then I will be really worried that a lot of people are not getting my updates properly.

**Comment by DallasO** [comment]
Mine updated properly, I saw the option in settings and it worked as expected.

**Comment by pistou** [comment]
It's alright now :+1: 
Probably a strange behavior from the updater
