### ISSUE TITLE
Left original pane gets brown fill colour, right diff pane remains empty

### ISSUE THREAD

**Issue by pamtbaau** [mupchrch/split-diff#4]
When opening `split-diff/diff panes` the left original file pane gets a brown fill colour and the right diff pane remains empty.

Running Windows 10
Atom 1.2.4

**Comment by easterwood** [comment]
Same problem here. The right diff pane remains empty.

Windows 7
Atom 1.2.4

**Comment by mupchrch** [comment]
I am not sure I understand. If you only have one pane open when you run split-diff, then a second right pane will open that allows you to paste in the text you want to diff the left pane against.

Let me know if that info doesn't address your problem!

**Comment by pamtbaau** [comment]
Ah, my bad. I didn't realise I had to copy/paste my own text into the second pane... After doing so, diffs are shown correctly.
I think I was mixing up with git-history which opens a second pane to show the diffs
