### ISSUE TITLE
Horizontal scrolling on both sides

### ISSUE THREAD

**Issue by iDev0urer** [mupchrch/split-diff#40]
Vertical scrolling works and will scroll both sides, horizontally does not however. This would be a nice feature to have

**Comment by mupchrch** [comment]
Hi, I may have some good news! Have you seen the "Sync Horizontal Scroll" setting in the package settings? I hope it will do exactly what you are asking for.

Let me know if there is anything else I can help with! (Or if I interpreted your question wrong :frowning:)
