### ISSUE TITLE
diff highlighting dissappears

### ISSUE THREAD

**Issue by kydan** [mupchrch/split-diff#41]
![animation](https://cloud.githubusercontent.com/assets/2177320/15107204/e91eb47c-1600-11e6-963f-70fa66daaa2d.gif)

As can be seen in the attached gif, when I try to toggle split-diff, the highlighting shows up for less than a second and then disappears. This is new as of the latest version of Atom I believe. 

window 10, atom 1.7.3, split-diff 0.7.5

**Comment by kydan** [comment]
since you cant get get at the dev console any longer, im not sure the best way to get any further info for you.

**Comment by mupchrch** [comment]
Thanks for the gif, I will try to reproduce on my Windows 10 machine tonight.

**Comment by kydan** [comment]
fwiw, I tried uninstalling and reinstalling the package a few times, which
kept failing as well. I removed atom completely, reinstalled and added
split-diff again an it worked fine. So, this may be a bit of a red herring
from a poor installation of atom.

Nick

**Comment by mupchrch** [comment]
Interesting, thanks for the update! I fixed a bug like the one you were showing, so it seems like you somehow got an older version of one of the package's files.

I get bugs like this from time to time regarding updates not working, so I wonder if it is my package, or if it is affecting other people's too.
