### ISSUE TITLE
After diffing is finished and split-diff is toggled closed, pane opened should be closed automatically

### ISSUE THREAD

**Issue by PombaM** [mupchrch/split-diff#48]

**Comment by mupchrch** [comment]
Is this not working for you? It seems to be fine for me.

Just to be sure, are you toggling on the package so that it creates the new pane for you? Split-diff closes any panes that it opened automatically. _Not_ panes that the user opened manually for diffing.

**Comment by PombaM** [comment]
Steps to reproduce:

Manually:
+ Right click on workspace
+ Select Split-Diff: Toggle

Command Palette:
+ `Ctrl+Shift+P` 
+ Type Split Diff 
+ Select Split Diff: Toggle / Split Diff: Enable

Observation:
In both cases after i toggle/disable, the  contents of pane disappears but the pane remains.

**Comment by mupchrch** [comment]
Do you have this core Atom setting unchecked?

![image](https://cloud.githubusercontent.com/assets/5797698/15473791/ccc27528-20cf-11e6-8788-82de1a2cea1c.png)

**Comment by PombaM** [comment]
No I don't but IMHO, the package should close the pane since the pane was created by the package itself not by the users.
