### ISSUE TITLE
Feature request: Go To Next/Previous Diff

### ISSUE THREAD

**Issue by drq883** [mupchrch/split-diff#5]
Coming from a tkdiff world, I loved the ability to skip to the various differences by pressing the N or P keys. Is something like this doable for this package?

**Comment by mupchrch** [comment]
Yes, I was actually planning to implement this as the next feature of the package, but got busy with some other projects. I will definitely focus on this as soon as I can!

**Comment by pistou** [comment]
:+1: Good to hear

**Comment by mupchrch** [comment]
The standard keybindings are ctrl-alt-n for next and ctrl-alt-p for previous. Let me know if you have any problems.

Happy diffing!

**Comment by drq883** [comment]
In testing, I'm seeing Atom lock up. As soon as I have more time, I'll try to post an example to reproduce the problem.
