### ISSUE TITLE
Copy to left / copy to right buttons UI question

### ISSUE THREAD

**Issue by mupchrch** [mupchrch/split-diff#55]
Does anyone have input about which order the copy to left / copy to right buttons should be in?

![image](https://cloud.githubusercontent.com/assets/5797698/15446308/6c5dbda0-1eea-11e6-89a2-d31cdab8ead6.png)

vs.

![image](https://cloud.githubusercontent.com/assets/5797698/15446325/09d27fb2-1eeb-11e6-8609-5460e537e3de.png)

For usability reasons, should the copy to right button be closer to the left editor? Or should the arrows remain facing outward?

---

Also, should the buttons have text so they are easier to understand?

![image](https://cloud.githubusercontent.com/assets/5797698/15526811/c1e0a3ee-2202-11e6-8255-7d6cff222782.png)

**Comment by iDev0urer** [comment]
@mupchrch I feel like the first one feels more natural. Have the button on the side you are copying to

**Comment by mupchrch** [comment]
I think I agree. That's what I went with for the latest release. Thanks!
