### ISSUE TITLE
Problems with Updates

### ISSUE THREAD

**Issue by DallasO** [mupchrch/split-diff#56]
You mentioned a while back in other issues (  https://github.com/mupchrch/split-diff/issues/41#issuecomment-218320297 and https://github.com/mupchrch/split-diff/issues/29#issuecomment-209004223 ) about problems with people getting your updates. Even though I **do** receive your updates, when I click the update button on your package in the package manager, the installing animation/message never stops. If I close the tab or click Check for Updates again, split-diff just disappears and says there are no updates. When I go back to split-diff, it says it is the new version.

Just adding this so hopefully people will contribute and this can get figured out. Is there any logging or something I can do to help? (I am just starting to teach myself how to write Atom packages, so I may not be much help in that regard)

**Comment by mupchrch** [comment]
Pushing out an update, hope it goes smoothly 🙏

**Comment by iDev0urer** [comment]
@mupchrch Went smoothly for me :+1:

**Comment by DallasO** [comment]
I still had the updating animation last for almost an hour before I think I did something that made it refresh and go away. Just re-installed Atom to see if it is an Atom bug or just my machine. I don't see anyone else reporting something similar on the Atom page. - Now if only I knew how to test the update again haha.

**Comment by mupchrch** [comment]
@DallasO I feel like the same thing happens to me whenever I update atom-beautify. The little update animation goes forever until I restart Atom. I wonder why random packages are affected like that.

**Comment by DallasO** [comment]
So after re-installing atom, I am still seeing this problem, but noticed it is happening with at least 1 other package. So I am assuming this is an atom problem. I will post this issue on there.

**Comment by mupchrch** [comment]
Haven't really seen this in a while. Feel free to reopen this issue if it is still occurring!
