### ISSUE TITLE
Option to turn off notifications.

### ISSUE THREAD

**Issue by ltegman** [mupchrch/split-diff#57]
I find that the majority of the time I use split diff it is self-evident when it is enabled and disabled, so the notification is simply a nuisance getting in the way of my code. Would you be amicable to a PR that added a config option to turn off notifications for this plugin?

**Comment by mupchrch** [comment]
I think that's a really good idea!

Although I am almost done making a UI footer bar with information and buttons, so maybe that would make that notification unnecessary. Perhaps I could remove it instead of making you add a setting? What do you think?

**Comment by ltegman** [comment]
I think that sounds like a great plan -- adding settings is never an ideal solution, so I think the footer would be a great alternative to having the notifications. Thanks for your hard work on this great plugin!
