### ISSUE TITLE
"Computing the diff for you" hang

### ISSUE THREAD

**Issue by jrie** [mupchrch/split-diff#65]
I have two files which I would like to diff, in general it did work smoothly.
But after adding more corner case content, it just keeps hanging at the "computing the diff"-modal.

This is the input I start diffing with (pane1):
[diff_new.txt](https://github.com/mupchrch/split-diff/files/361223/diff_new.txt)

This is the original file I want to diff with (pane2):
[diff_org.txt](https://github.com/mupchrch/split-diff/files/361222/diff_org.txt)

The content that has been added, what seems to caused issues, looked like that:

```
{| align=&quot;center&quot; cellspacing=&quot;10&quot;
|- align=&quot;center&quot;
|[[Image:EgyptianA-01.png|Egyptian hieroglyphic ox head]]&lt;br /&gt;Egyptian hieroglyph&lt;br /&gt;ox head
|[[Image:Proto-semiticA-01.png|Proto-semitic ox head]]&lt;br /&gt;Proto-semitic&lt;br /&gt;ox head
|[[Image:PhoenicianA-01.png|Phoenician aleph]]&lt;br /&gt;Phoenician ''aleph''
|[[Image:GreekA-01.png|Greek alpha]]&lt;br /&gt;Greek ''alpha''
|[[Image:EtruscanA-01.png|Etruscan A]]&lt;br /&gt;Etruscan A
|[[Image:RomanA-01.png|Roman A]]&lt;br /&gt;Roman A
|}
```

In example at the very bottom of the file, from line 2153 to 2161.
But there are more of this Wikipedia Table declarations.

Any help would be appreciated.

**Comment by jrie** [comment]
More feedback:
In fact, it does not in particular be the table markup... I checked the file once more and I only could see this one table declaration. I was thinking there have been more.

Even when this particular part is removed, the computing modal stays open.

Im just not exactly sure where or why it hangs.

**Comment by mupchrch** [comment]
It is definitely hanging for me with your files. I will keep investigating, thanks for providing the example files!

**Comment by gelgin2k** [comment]
I'll try to provide additional files, at the moment I'm working with customer info so can't share that.  Basically getting the same hang event on medium sized XML files.  These particular ones are firewall configuration files. 

The XML files are well behaved (tags match up etc.)  so not malformed in that sense. 

Let me know if there is additional information you would like.

**Comment by luisdavim** [comment]
I'm having the same issue comparing two large json files.
