### ISSUE TITLE
Service API

### ISSUE THREAD

**Issue by benoitcerrina** [mupchrch/split-diff#69]
Hello,
I am using the file-watcher package which warning when a file modified in atom is modified in another editor to avoid overwriting it.  This package offers the choice to compare the modified file with the version in the atom buffer.  This opens a side by side panel but does not highlight the diffs.   I am now using split-diff for that purpose.  I did that by calling the toggle command explicitly when the compare choice is made.  

>   atom.commands.dispatch(document.querySelector('atom-text-editor'), 'split-diff:toggle')

It would be better if split-diff was using the service api to expose directly this functionality to other packages. What do you think?

**Comment by mupchrch** [comment]
Hi @benoitcerrina, thanks for the feedback! Sorry this is so late, what sort of functionality would be helpful? Would you just need to be able to turn on split diff? Would you want to be able to pass in specific text editors for diffing? Both?

**Comment by benoitcerrina** [comment]
Hello,
For my specific use case just turning it on would have been enough. But from a more generic point of view being able to specify the text editors as an option would be more useful

**Comment by mupchrch** [comment]
Check README for service API documentation

**Comment by benoitcerrina** [comment]
Great, thanks.
