### ISSUE TITLE
Word wrap (soft wrap) gets ignored

### ISSUE THREAD

**Issue by rajnisheu** [mupchrch/split-diff#71]
When opening another window from split pane, all is fine and word wrap works. When panes are opened using split-diff, lines are not wrapped and its hard to scroll. There is the option of horizontal scroll, but its not very helpful unfortunately.
Any way this could be solved?
Thanks for a great package btw, this is the best one I found for git-diff! Was missing this coming from netbeans.

**Comment by mupchrch** [comment]
Thanks! Glad you like the package.

I can probably make split-diff panes default to the user's word wrap setting. I think I didn't do that because soft wrap makes it so the differences between the panes are not aligned next to each other, but I can see why users would just want it to copy their settings.

**Comment by rajnisheu** [comment]
I can guess what you mean with alignment issue/s. With long lines, it is especially hard to keep in sync  if there are several changes. If yo are interested, I am pasting a screenshot from netbeans if you are interested as an example of long statements wrapping. usual for me, and, probably for lot of users.

Diffs have really got me worked up in atom. I am just able to find a decent set of tools/packages to get a list of files properly. Been struggling for nearly a full day. Just for sake of sharing, am posting another image showing how netbeans creates a very decent table of files changed. Just don't understand why is this rocket science in atom, or maybe I am missing something fundamental.

Your is the only decent looking, bug free and stable diff for files I could find.. also the reason for my compliments for your work!
image 1
![image](https://cloud.githubusercontent.com/assets/9862417/18917285/4ee5f01a-858f-11e6-9b41-d6e4481c9f35.png)

image 2 (partial image)
![image](https://cloud.githubusercontent.com/assets/9862417/18917914/fcbc0782-8590-11e6-89b5-756962917030.png)

**Comment by mupchrch** [comment]
I'm not sure if you've found this already in your search, but I found this rudimentary package for seeing a git status: https://atom.io/packages/git-status

**Comment by rajnisheu** [comment]
Thanks! Yes, I did. That feature is built-in into tree-view. One can navigate into each folder to see files individually, but that's cumbersome.
