### ISSUE TITLE
copy-left and copy-right didn't always work

### ISSUE THREAD

**Issue by azuruce** [mupchrch/split-diff#73]
I can sometimes open split-diff and I try to navigate using shortcut keys to next or prev diff. Then I try to revert selected diff if I don't want it. The problem is if a line is added and I click the button to copy right to left, it will error and say I need to put the cursor at a line of change. Supposedly since I added a line to the left and now I want to copy right to left, there is no line in the right that corresponding to the "add", therefore, it will error.

There is no short-cut key for copy-left and copy-right. I thought that's the main reason we use diff. It made me think the diff and revert feature might not work very well so no one creates a shortcut for it?

**Comment by boaz-amit** [comment]
While I did not experience the bug described, I second the request for the copy-left and copy-right key bindings. Thank you.

**Comment by boaz-amit** [comment]
@azuruce Looking in the package's source, apparently there is already undocumented support for copy-left and copy-right shortcuts.

In your `keymap.cson` file, you can add the following:

     'atom-workspace':
        'alt-up': 'split-diff:prev-diff'
        'alt-down': 'split-diff:next-diff'
        'alt-right': 'split-diff:copy-to-right'
        'alt-left': 'split-diff:copy-to-left'

The above key bindings are just my personal preference. You should replace them with your own.

**Comment by mupchrch** [comment]
@azuruce I think I understand what you're saying. If there is an added line in the left and no corresponding line in the right and you hit the "copy to left" button, it will tell you that you need to have your cursor in a diff chunk. I believe this is expected behavior (at the moment).

What would you expect to happen in this scenario? Would the line in the left be erased?

---

@boaz-amit I am always hesitant to add default keybindings since I wouldn't want to override another package's / another user's keybindings. But it would be nice to have, I'll look into it further.

**Comment by boaz-amit** [comment]
@mupchrch I'm in complete agreement. I would only suggest that the names of the commands would be listed in the settings unassigned (if technically possible) and/or appear in the documentation. This would make users aware of their existence and allow them to set their own bindings. Thanks again for all your hard work!

**Comment by azuruce** [comment]
@mupchrch, you got my point! copy left when a line is added should remove that line. That's the behavior on all other diff tools at least in emacs. Also can you limit your keybinding to split-diff window? I thought the string 'atom-workspace' says binding will work in all windows? Thanks for the great work!

**Comment by mupchrch** [comment]
README has been updated with commands so users know they can override them with custom keybindings (via #76)

**Comment by boaz-amit** [comment]
@mupchrch Thanks again!
