### ISSUE TITLE
add a changelog

### ISSUE THREAD

**Issue by benoitcerrina** [mupchrch/split-diff#77]
Hello,
noticed new 1.06 version and was looking for what was new.  Atom is expecting a CHANGELOG.md file which wasn't there.  I had to resort to looking at the git commits between 1.05 and 1.06 and was made happy by the changes I found since I had run in the exact issues which have been fixed.  Just too bad I couldn't see it from the editor.  
So I think a changelog would be nice

**Comment by mupchrch** [comment]
Hmm, I wonder if your installation partially failed. There is definitely a `CHANGELOG.md` file. (However, I definitely messed up the version numbering inside this latest one).

I'm curious if you uninstalled and reinstalled the package, would the changelog show up?

-

And just to be clear, you're referring to this button not appearing, correct?
![image](https://cloud.githubusercontent.com/assets/5797698/19730772/426bc4dc-9b69-11e6-831b-c50bbe8ec2c4.png)
