### ISSUE TITLE
New Feature: Colour picker

### ISSUE THREAD

**Issue by laurenblackfox** [mupchrch/split-diff#78]
So, I'm red/green colourblind, and I can't see the code when it's highlighted. I need to be able to change the colours the added/removed highlights use. It's kind of an accessibility issue I'm sure others would benefit from too.

**Comment by mupchrch** [comment]
Definitely agree! I wanted to do this when I implemented the option to change between red/green, but wasn't sure how to dynamically change the color of those line markers. Not sure the Atom API has a way of doing that yet.

In the mean time, you can actually style those line highlights in your user stylesheet:

```
.split-diff-added,
::shadow .split-diff-added {
  background-color: fade(blue, 40%) !important;
}

.minimap .added {
  background: blue !important;
}

.split-diff-removed,
::shadow .split-diff-removed {
  background-color: fade(blue, 40%) !important;
}

.minimap .removed {
  background: blue !important;
}
```

Hope that helps at least a little bit, while I work on implementing an actual color picker!

**Comment by megamaiku** [comment]
Thaaaaaaank youuuuuu!!! lol

**Comment by megamaiku** [comment]
The first part of the code block works for me: 
```
.split-diff-added,
::shadow .split-diff-added {
  background-color: fade(blue, 40%) !important;
}

.minimap .added {
  background: blue !important;
}
```
But this second portion doesn't do anything. I try to remove a word on the left to see if it gets a highlight on the right, but it just shows the removed word without a highlight. Not sure if I'm doing something wrong here.
```
.split-diff-removed,
::shadow .split-diff-removed {
  background-color: fade(red, 40%) !important;
}

.minimap .removed {
  background: red !important;
}
```

Thanks a lot for putting time into this project!

**Comment by mupchrch** [comment]
Dang, @megamaiku, I investigated your problem a bit when I read your message and totally forgot to reply! Really sorry about that.

Did you ever figure out the issue? I wasn't able to reproduce it with my setup. What syntax theme are you using?

Also, as a note, you can remove the `::shadow` selectors from that css, they are no longer needed as of Atom v1.13
