### ISSUE TITLE
Hide tree-view while showing split diff

### ISSUE THREAD

**Issue by ivanaugustobd** [mupchrch/split-diff#82]
First, thanks for this package! 😄
I'm using meld for some weeks and today I discovered this package. The biggest difference I noticed is the horizontal space used by both. Meld don't have a tree view/sidebar, so it occupy less space in screen, given a "better" reading. Currently, I'm hiding manualy the tree view when open split diff. It's possible to make this automaticly while split diff is open? Something like shot the tree-view:toggle after the split-diff:toggle.. 🤔

**Comment by mupchrch** [comment]
Hi, you can add the below code to your user init script to accomplish what you are asking.

```
atom.commands.add('atom-workspace', 'split-diff:toggle', () ->
  atom.commands.dispatch(document.querySelector('atom-text-editor'), 'tree-view:toggle')
)
```

Let me know if there's anything else I can help you with!

**Comment by ivanaugustobd** [comment]
Worked perfectly, thanks! :smile:
Maybe this can be an option on package settings.. :thinking:

**Comment by mupchrch** [comment]
Oh, didn't even cross my mind! I can't think of a reason why it couldn't be an option, great idea.
