### ISSUE TITLE
Show Word Diff has no effect

### ISSUE THREAD

**Issue by pitkling** [mupchrch/split-diff#89]
Show Word Diff seems to be broken. It doesn't have any effect for me (see image).
<img width="1208" alt="screen shot 2017-01-28 at 18 33 36" src="https://cloud.githubusercontent.com/assets/1018801/22398414/7239e1d0-e588-11e6-9bea-04393415b792.png">

**Comment by mupchrch** [comment]
Hi @pitkling, which UI Theme are you using? Which syntax theme?

If changing one of your themes fixes the problem, we may need to log an issue against that theme. Split diff uses colors that are defined in the theme.

**Comment by pitkling** [comment]
Ahh, that makes sense. The problem is the Seti syntax theme I'm using.

**Comment by mupchrch** [comment]
Hm okay, I'll keep looking at this. From the quick glance I just took, I feel like it should be working. `seti-syntax` doesn't appear like it's doing anything strange.

**Comment by mupchrch** [comment]
Looks like there is some code in `seti-syntax` theme that overrides my line marker styling. [Relevant code from seti-syntax](https://github.com/jesseweed/seti-syntax/blob/597021a22133e835c88462ca070bd97b915cf6f5/styles/plugins/git-time-machine.less#L3). I'll log an issue over there for you.

**Comment by mupchrch** [comment]
Closing as this is more of an issue with seti-syntax.
