### ISSUE TITLE
Unable to use file tree to diff files

### ISSUE THREAD

**Issue by mupchrch** [mupchrch/split-diff#9]
I would like to be able to use the file tree to select files for diff.

**Comment by mupchrch** [comment]
Now that I think about it, I am not sure that this is a very important feature. Will probably close this soon if no one says anything.

**Comment by DallasO** [comment]
I would find this very useful

**Comment by mike-kelly** [comment]
Absolutely, very important feature IMO.

**Comment by protokris** [comment]
Just got this package and shocked it doesn't do this... can I not diff 2 arbitrary files?

**Comment by mupchrch** [comment]
@protokris You can, but you need to have the two files split side by side. One way to do that is open your two files, right click the tab for one of them and select split right. Then toggle split-diff with the two files you want to diff visible next to each other.

Not the greatest user experience at all, I definitely agree... Hopefully now that I've finished refactoring, features like this should be much easier to implement.

**Comment by mupchrch** [comment]
Sorry for the long wait, everybody. This is in v1.1.0, which I will be pushing out now.
