### ISSUE TITLE
Editor Color

### ISSUE THREAD

**Issue by kenitive** [mupchrch/split-diff#90]
Hello,

I have been encountering with this issue for a long time.
Every time when I update the package, my settings for colors resets.

**Atom**: 1.13.0 x64
**System**: Ubuntu 16.04 LTS
**Thrown From**: split-diff package, v1.1.1

![image](https://cloud.githubusercontent.com/assets/5467717/22419491/6d036c86-e6e6-11e6-9ae9-c16044f8ed6d.png)

**Comment by mupchrch** [comment]
Hi, are your settings reflected in your atom config file? They probably will be, just want to make sure. If you're unsure, feel free to paste it here, thanks!

Is it just those two settings? Have you noticed any other settings get changed on you? Even in other packages?

Thanks!

**Comment by kenitive** [comment]
@mupchrch Before I config the package I have this config file
```
...
"split-diff":
    ignoreWhitespace: true
    leftEditorColor: "red"
    rightEditorColor: "green"
    syncHorizontalScroll: true
...
```

But when I change colors (left: green, right: red), my config file looks like this:
```
...
"split-diff":
    ignoreWhitespace: true
    syncHorizontalScroll: true
...
```

**Comment by mupchrch** [comment]
Awesome, thanks. I'll try to set up a way to simulate package update to see if I can experience the problem.

FYI, the colors go away in your second example because you are setting them back to their default states so your config file doesn't need to override them in that case. I wonder why upgrading your package would alter your config back to defaults 😞

**Comment by kenitive** [comment]
@mupchrch I've found the problem. The problem is called **sync-settings**. For a long time I didn't sync my atom config. Every time when I update Atom, config restores from old version. In old version colors are wrong for me. 
Sorry 🙃
