### ISSUE TITLE
ctrl + alt + t shortcut conflicts with terminal on Linux

### ISSUE THREAD

**Issue by nloomans** [mupchrch/split-diff#98]
On most Linux systems <kbd>ctr</kbd> + <kbd>alt</kbd> + <kbd>t</kbd> is set as the default shortcut for opening the terminal, this prevents the default shortcut for toggling the diff view from working.

I suggest changing it to something else.

**Comment by martinruenz** [comment]
As all split-diff commands are <kbd>ctr</kbd> + <kbd>alt</kbd> based, how about <kbd>ctr</kbd> + <kbd>alt</kbd> + <kbd>d</kbd>, as for **d**iff?
In the past this combination was used on some systems to show the desktop, but I think not anymore. Definitely better than the very common <kbd>ctr</kbd> + <kbd>alt</kbd> + <kbd>t</kbd>.
